complete react-accordion-component
hoangnguyen9384/m3-1120-code-solutions pull request #17
Opened 2020-12-09 07:09 UTC by hoangnguyen9384

<img width="861" alt="Screen Shot 2020-12-08 at 11 06 34 PM" src="https://user-images.githubusercontent.com/63882540/101596666-5ba9a480-39aa-11eb-95d7-0daaeafe77fb.png">
<img width="789" alt="Screen Shot 2020-12-08 at 11 06 49 PM" src="https://user-images.githubusercontent.com/63882540/101596667-5cdad180-39aa-11eb-9a79-4e7107ebad0d.png">
<img width="824" alt="Screen Shot 2020-12-08 at 11 07 06 PM" src="https://user-images.githubusercontent.com/63882540/101596669-5e0bfe80-39aa-11eb-9946-c581ad06e610.png">
<img width="935" alt="Screen Shot 2020-12-08 at 11 07 15 PM" src="https://user-images.githubusercontent.com/63882540/101596674-5ea49500-39aa-11eb-9bf2-b31792304ae7.png">

2020-12-11 04:55 UTC, scbowler requested changes
Interesting solution, only issue is that the topics data needs to be in an array and passed into the accordion via props then the jsx needs to be dynamically created in the accordion by looping through the topics data. See below comments for more details. Let me know if you have any questions.

2020-12-11 04:55 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +        </App>
This structure should be created dynamically. The topics data should be created as an array in the `index.jsx` file then passed to accordion via props.

2020-12-11 04:55 UTC, scbowler commented on react-accordion-component/src/index.jsx
> +
Create the array of topics here

2020-12-11 04:55 UTC, scbowler commented on react-accordion-component/src/index.jsx
> +  <Accordion />,
Pass array of topics to accordion here via props

```JSX
<Accordion topics={topicsData} />
```

2020-12-19 18:04 UTC, Zhiwutian approved these changes
👍

2020-12-19 18:09 UTC, merged